version: '3'

services:
  app:
    container_name: reportanalyser
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=9000
    working_dir: /simple-app
    networks:
      - coolify-infra
    labels:
      # Traefik Configuration
      - "traefik.enable=true"
      - "traefik.http.routers.app-uos88s8kwg4cocsscsc0w4ww.rule=Host(`kyle.app.kimuse.rw`)"
      - "traefik.http.routers.app-uos88s8kwg4cocsscsc0w4ww.entrypoints=web,websecure"
      - "traefik.http.services.app-uos88s8kwg4cocsscsc0w4ww.loadbalancer.server.port=9000"
      # Important: Specify the correct service for Traefik
      - "traefik.http.routers.app-uos88s8kwg4cocsscsc0w4ww.service=app-uos88s8kwg4cocsscsc0w4ww"
      # Health check settings
      - "traefik.http.services.app-uos88s8kwg4cocsscsc0w4ww.loadbalancer.healthcheck.path=/health"
      - "traefik.http.services.app-uos88s8kwg4cocsscsc0w4ww.loadbalancer.healthcheck.interval=10s"
      - "traefik.http.services.app-uos88s8kwg4cocsscsc0w4ww.loadbalancer.healthcheck.timeout=5s"

networks:
  coolify-infra:
    external: true 