version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      PORT: 9000
    labels:
      - traefik.enable=true
      - "traefik.http.routers.reportanalyser.rule=Host(`${HOST_DOMAIN}`)"
      - traefik.http.routers.reportanalyser.entryPoints=http
      - "traefik.http.routers.reportanalyser-secure.rule=Host(`${HOST_DOMAIN}`)"
      - traefik.http.routers.reportanalyser-secure.entryPoints=https
      - traefik.http.routers.reportanalyser-secure.tls=true
      - "traefik.http.services.reportanalyser.loadbalancer.server.port=9000" 