version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      NODE_ENV: development
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 